first commit
maksym-bakunov/online-book-store pull request #1
Opened 2024-04-15 20:56 UTC by maksym-bakunov

2024-04-16 06:57 UTC, Elena-Bruyako requested changes
It looks like your project tree is wrong. pom file and gitignore file should be below of src package.

2024-04-16 06:57 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/OnlineBookStoreApplication.java
> +
```suggestion
```

2024-04-16 06:57 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/Book.java
> +@Table(name = "book")
Tables should be names as plural

2024-04-16 06:57 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/Book.java
> +    @Column(name = "id")
it's redundant

2024-04-16 06:57 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/Book.java
> +    public Book() {
Why do you need this constructor?

2024-04-16 06:57 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/Book.java
> +    private Currency price;
```suggestion
    private BigDecimal price;
```

2024-04-16 06:57 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/impl/BookServiceImp.java
> +public class BookServiceImp implements BookService {
```suggestion
public class BookServiceImpl implements BookService {
```

2024-04-16 06:57 UTC, Elena-Bruyako commented on src/main/resources/application.properties
> +spring.jpa.show-sql = true
```suggestion
spring.jpa.show-sql=true
```

2024-04-16 22:14 UTC, maksym-bakunov commented
> It looks like your project tree is wrong. pom file and gitignore file should be below of src package.

What do you mean? Bellow is the screen of my project:
https://c2n.me/4kI0ICr

2024-04-17 10:00 UTC, kozhukhovsky approved these changes

2024-04-17 10:00 UTC, kozhukhovsky commented on src/main/java/com/example/onlinebookstore/OnlineBookStoreApplication.java
> +
```suggestion
```

2024-04-19 09:10 UTC, merged