Solution (Spring Boot Data JPA).
maksym-bakunov/online-book-store pull request #3
Opened 2024-09-11 13:31 UTC by maksym-bakunov

2024-09-11 13:51 UTC, Elena-Bruyako requested changes
see comments

2024-09-11 13:51 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/controller/BookController.java
> +    public BookDto putBook(@PathVariable Long id, @RequestBody CreateBookRequestDto bookDto) {
```suggestion
    public BookDto update(@PathVariable Long id, @RequestBody CreateBookRequestDto bookDto) {
```

2024-09-11 13:51 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/Book.java
>  @NoArgsConstructor
```suggestion
```

2024-09-11 13:51 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/Book.java
> +    @Column(name = "is_deleted")
remove all @Column(name..) hibernate automatically creates column in snake_case format

2024-09-11 13:51 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/impl/BookServiceImpl.java
> +        }).orElseThrow(() -> new EntityNotFoundException("Can't find book by id " + id));
```suggestion
        Book book = bookRepository.findById(id)
                .orElseThrow(()...
        bookMapper.updateBookFromDto(bookDto, book);
        bookRepository.save(book);
        return bookMapper.toDto(book);
```

2024-09-12 08:13 UTC, okuzan approved these changes

2024-09-12 15:05 UTC, merged